#! /usr/bin/env node

const inquirer = require('inquirer');
const path = require('path');
const chalk = require('chalk');
const fs = require('fs');
const child_process = require('child_process');
const pkg = require(path.resolve(process.cwd(), 'package.json')) || {};
const config = require('./config');
const questions = [
  {
    type: 'input',
    name: 'name',
    message: 'What\'s your project name. ',
    default: function() {
      return pkg.name || '';
    }
  },
  {
    type: 'list',
    name: 'type',
    message: 'which environment will you publish, daily or publish？',
    choices: ['daily', 'publish']
  },
  {
    type: 'input',
    name: 'version',
    message: 'Please input the project version, i.e. "1.0.1". ',
    default: function() {
      const output = fs.readFileSync(path.resolve(process.cwd(), config.gitHead), 'utf-8');
      const result = output.match(/refs\/heads\/daily\/(([0-9]{1,2}\.){2}[0-9]{1,2})/);
      return result && result[1] || '';
    },
    validate: function(version) {
      if(/^([0-9]{1,2}\.){2}[0-9]{1,2}$/.test(version)) {
        var files = [];
        try {
          // git文件取branch得优化下。
          files = fs.readdirSync(path.resolve(process.cwd(), config.gitDirBranch));
        } catch(err) {
          console.log(`\n\n  ${chalk.red('The git files is non-existent!')}`);
          process.exit(0);
        }
        if (~files.indexOf(version)) {
          return true;
        }
        return 'the version is non-existent, input again！'
      }
      return 'Please input the correct version, i.e. "1.0.1"'
    }
  }
];

var execSh = function(item) {
  return new Promise((resolve, reject) => {
    console.log((`\n${chalk.cyan('executing:')} ${chalk.red(item.command)}`));
    ls = child_process.exec(item.command, { encoding: 'utf8' });
    ls.stdout.on('data', function(data) {
      console.log(data);
      item.errfn && item.errfn(data);
    });
    ls.stderr.on('data', function(data) {
      console.log(data);
      item.errfn && item.errfn(data);
    });
    ls.on('close', () => {
      resolve();
    });
  });
}

var pub = async function () {
  inquirer.prompt(questions).then(function(content) {
    const commands = config.commands(content);
    (async function(){
      for (var i = 0; i < commands.length; i += 1) {
        await execSh(commands[i]);
      }
      console.log(chalk.green(`publish "${content.type}/${content.version}" successfully!`));
    })();    
  });
}

pub();
